version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  "frontend build and test":
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                command: npm install
                working_directory: src/frontend
            - run:
                command: npm test
                working_directory: src/frontend
workflows:
    "build and test":
      jobs:
        - "frontend build and test"
