version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  "frontend build and test":
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          working_directory: src/frontend
          steps:
            - run: npm install
            - run: npm test
workflows:
    "build and test":
      jobs:
        - "frontend build and test"
